### ISSUE TITLE
Conda dist

### ISSUE THREAD

**Issue by ZarulHanifah** [flexidot-bio/flexidot#11]
Hello Flexidot team,

I can't use the software, it kept giving an error. Here is it:

```
$ python2 ../flexidot/code/flexidot_v1.05.py -h
Installing Python module: matplotlib
	python -m pip install --upgrade matplotlib

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: matplotlib in /home/zarul/.local/lib/python2.7/site-packages (2.2.4)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /home/zarul/.local/lib/python2.7/site-packages (from matplotlib) (2.8.1)
Requirement already satisfied, skipping upgrade: subprocess32 in /home/zarul/.local/lib/python2.7/site-packages (from matplotlib) (3.5.4)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in /home/zarul/.local/lib/python2.7/site-packages (from matplotlib) (0.10.0)
Requirement already satisfied, skipping upgrade: six>=1.10 in /home/zarul/.local/lib/python2.7/site-packages (from matplotlib) (1.14.0)
Requirement already satisfied, skipping upgrade: backports.functools-lru-cache in /home/zarul/.local/lib/python2.7/site-packages (from matplotlib) (1.6.1)
Requirement already satisfied, skipping upgrade: pytz in /home/zarul/.local/lib/python2.7/site-packages (from matplotlib) (2019.3)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/zarul/.local/lib/python2.7/site-packages (from matplotlib) (2.4.6)
Requirement already satisfied, skipping upgrade: numpy>=1.7.1 in /home/zarul/.local/lib/python2.7/site-packages (from matplotlib) (1.16.6)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in /home/zarul/.local/lib/python2.7/site-packages (from matplotlib) (1.1.0)
Requirement already satisfied, skipping upgrade: setuptools in /home/zarul/.local/lib/python2.7/site-packages (from kiwisolver>=1.0.1->matplotlib) (44.0.0)


Please install module matplotlib manually
Traceback (most recent call last):
  File "../flexidot/code/flexidot_v1.05.py", line 3315, in <module>
    load_modules()
  File "../flexidot/code/flexidot_v1.05.py", line 61, in load_modules
    import matplotlib.colors as mcolors
  File "/home/zarul/.local/lib/python2.7/site-packages/matplotlib/__init__.py", line 126, in <module>
    from . import cbook
  File "/home/zarul/.local/lib/python2.7/site-packages/matplotlib/cbook/__init__.py", line 34, in <module>
    import numpy as np
  File "/home/zarul/.local/lib/python2.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init

```

Can you provide it in conda distribution through the bioconda channel please?

**Comment by Jeremias-Brand** [comment]
While there is no conda dist I found that you can run it by installing all the dependencies into a conda env.

```
channels:
 - bioconda
dependencies:
 - python=2.7
 - numpy
 - matplotlib
 - biopython
 - regex
 - colormap
 - colour
```

So you do:
```
conda create -n flexidot python=2.7 numpy matplotlib biopython regex colormap colour
conda activate flexidot
```

Then run the script in that env.
